Flex Bison C++ Example: CNDivide Class Reference
CNDivide Class Reference
Calculation node dividing two operand nodes.
#include <expression.h>
Public Member Functions
CNDivide (CalcNode *_left, CalcNode *_right)
virtual ~CNDivide ()
virtual double evaluate () const
evaluate the complete calculation tree and return the floating point result value
virtual void print (std::ostream &os, unsigned int depth) const
output the calculation tree to the given stream.
Public Member Functions inherited from CalcNode
virtual ~CalcNode ()
required for virtual functions.
Private Attributes
CalcNode * left
left calculation operand
CalcNode * right
right calculation operand
Additional Inherited Members
Static Public Member Functions inherited from CalcNode
static std::string indent (unsigned int d)
helper function for print() which makes the indention string
Detailed Description
Calculation node dividing two operand nodes.
Definition at line 195 of file expression.h.
Constructor & Destructor Documentation
CNDivide::CNDivide (CalcNode * _left, CalcNode * _right) inline explicit
Definition at line 204 of file expression.h.
virtual CNDivide::~CNDivide () inline virtual
Definition at line 209 of file expression.h.
References left, and right.
Member Function Documentation
virtual double CNDivide::evaluate () const inline virtual
evaluate the complete calculation tree and return the floating point result value
Implements CalcNode.
Definition at line 215 of file expression.h.
References CalcNode::evaluate(), left, and right.
virtual void CNDivide::print (std::ostream & os, unsigned int depth) const inline virtual
output the calculation tree to the given stream.
tries to format the output to make tree levels visible.
Implements CalcNode.
Definition at line 220 of file expression.h.
References CalcNode::indent(), left, CalcNode::print(), and right.
Member Data Documentation
CalcNode* CNDivide::left private
left calculation operand
Definition at line 198 of file expression.h.
Referenced by evaluate(), print(), and ~CNDivide().
CalcNode* CNDivide::right private
right calculation operand
Definition at line 201 of file expression.h.
Referenced by evaluate(), print(), and ~CNDivide().
The documentation for this class was generated from the following file:
src/expression.h