Flex Bison C++ Example: CNModulo Class Reference
CNModulo Class Reference
Calculation node calculating the remainder of an integer division of two operand nodes.
#include <expression.h>
Public Member Functions
CNModulo (CalcNode *_left, CalcNode *_right)
virtual ~CNModulo ()
virtual double evaluate () const
evaluate the complete calculation tree and return the floating point result value
virtual void print (std::ostream &os, unsigned int depth) const
output the calculation tree to the given stream.
Public Member Functions inherited from CalcNode
virtual ~CalcNode ()
required for virtual functions.
Private Attributes
CalcNode * left
left calculation operand
CalcNode * right
right calculation operand
Additional Inherited Members
Static Public Member Functions inherited from CalcNode
static std::string indent (unsigned int d)
helper function for print() which makes the indention string
Detailed Description
Calculation node calculating the remainder of an integer division of two operand nodes.
Definition at line 230 of file expression.h.
Constructor & Destructor Documentation
CNModulo::CNModulo (CalcNode * _left, CalcNode * _right) inline explicit
Definition at line 239 of file expression.h.
virtual CNModulo::~CNModulo () inline virtual
Definition at line 244 of file expression.h.
References left, and right.
Member Function Documentation
virtual double CNModulo::evaluate () const inline virtual
evaluate the complete calculation tree and return the floating point result value
Implements CalcNode.
Definition at line 250 of file expression.h.
References CalcNode::evaluate(), left, and right.
virtual void CNModulo::print (std::ostream & os, unsigned int depth) const inline virtual
output the calculation tree to the given stream.
tries to format the output to make tree levels visible.
Implements CalcNode.
Definition at line 255 of file expression.h.
References CalcNode::indent(), left, CalcNode::print(), and right.
Member Data Documentation
CalcNode* CNModulo::left private
left calculation operand
Definition at line 233 of file expression.h.
Referenced by evaluate(), print(), and ~CNModulo().
CalcNode* CNModulo::right private
right calculation operand
Definition at line 236 of file expression.h.
Referenced by evaluate(), print(), and ~CNModulo().
The documentation for this class was generated from the following file:
src/expression.h