Flex Bison C++ Example: CNMultiply Class Reference
CNMultiply Class Reference
Calculation node multiplying two operand nodes.
#include <expression.h>
Public Member Functions
CNMultiply (CalcNode *_left, CalcNode *_right)
virtual ~CNMultiply ()
virtual double evaluate () const
evaluate the complete calculation tree and return the floating point result value
virtual void print (std::ostream &os, unsigned int depth) const
output the calculation tree to the given stream.
Public Member Functions inherited from CalcNode
virtual ~CalcNode ()
required for virtual functions.
Private Attributes
CalcNode * left
left calculation operand
CalcNode * right
right calculation operand
Additional Inherited Members
Static Public Member Functions inherited from CalcNode
static std::string indent (unsigned int d)
helper function for print() which makes the indention string
Detailed Description
Calculation node multiplying two operand nodes.
Definition at line 161 of file expression.h.
Constructor & Destructor Documentation
CNMultiply::CNMultiply (CalcNode * _left, CalcNode * _right) inline explicit
Definition at line 170 of file expression.h.
virtual CNMultiply::~CNMultiply () inline virtual
Definition at line 175 of file expression.h.
References left, and right.
Member Function Documentation
virtual double CNMultiply::evaluate () const inline virtual
evaluate the complete calculation tree and return the floating point result value
Implements CalcNode.
Definition at line 181 of file expression.h.
References CalcNode::evaluate(), left, and right.
virtual void CNMultiply::print (std::ostream & os, unsigned int depth) const inline virtual
output the calculation tree to the given stream.
tries to format the output to make tree levels visible.
Implements CalcNode.
Definition at line 186 of file expression.h.
References CalcNode::indent(), left, CalcNode::print(), and right.
Member Data Documentation
CalcNode* CNMultiply::left private
left calculation operand
Definition at line 164 of file expression.h.
Referenced by evaluate(), print(), and ~CNMultiply().
CalcNode* CNMultiply::right private
right calculation operand
Definition at line 167 of file expression.h.
Referenced by evaluate(), print(), and ~CNMultiply().
The documentation for this class was generated from the following file:
src/expression.h