Flex Bison C++ Example: CNSubtract Class Reference
CNSubtract Class Reference
Calculation node subtracting two operand nodes.
#include <expression.h>
Public Member Functions
CNSubtract (CalcNode *_left, CalcNode *_right)
virtual ~CNSubtract ()
virtual double evaluate () const
evaluate the complete calculation tree and return the floating point result value
virtual void print (std::ostream &os, unsigned int depth) const
output the calculation tree to the given stream.
Public Member Functions inherited from CalcNode
virtual ~CalcNode ()
required for virtual functions.
Private Attributes
CalcNode * left
left calculation operand
CalcNode * right
right calculation operand
Additional Inherited Members
Static Public Member Functions inherited from CalcNode
static std::string indent (unsigned int d)
helper function for print() which makes the indention string
Detailed Description
Calculation node subtracting two operand nodes.
Definition at line 127 of file expression.h.
Constructor & Destructor Documentation
CNSubtract::CNSubtract (CalcNode * _left, CalcNode * _right) inline explicit
Definition at line 136 of file expression.h.
virtual CNSubtract::~CNSubtract () inline virtual
Definition at line 141 of file expression.h.
References left, and right.
Member Function Documentation
virtual double CNSubtract::evaluate () const inline virtual
evaluate the complete calculation tree and return the floating point result value
Implements CalcNode.
Definition at line 147 of file expression.h.
References CalcNode::evaluate(), left, and right.
virtual void CNSubtract::print (std::ostream & os, unsigned int depth) const inline virtual
output the calculation tree to the given stream.
tries to format the output to make tree levels visible.
Implements CalcNode.
Definition at line 152 of file expression.h.
References CalcNode::indent(), left, CalcNode::print(), and right.
Member Data Documentation
CalcNode* CNSubtract::left private
left calculation operand
Definition at line 130 of file expression.h.
Referenced by evaluate(), print(), and ~CNSubtract().
CalcNode* CNSubtract::right private
right calculation operand
Definition at line 133 of file expression.h.
Referenced by evaluate(), print(), and ~CNSubtract().
The documentation for this class was generated from the following file:
src/expression.h